import mongoose, { Schema } from 'mongoose';

const PaymentSchema = new Schema({
  _id: { type: String, required: true }, // unique payment ID (e.g., pay_...)
  orderIds: { type: [String], required: true }, // IDs of all orders generated by this checkout
  customerId: { type: String, required: true, index: true },
  amount: { type: Number, required: true },
  method: { type: String, enum: ['razorpay', 'cod'], required: true },
  status: { type: String, enum: ['pending', 'paid', 'failed', 'refunded'], default: 'pending' },
  razorpayOrderId: { type: String },
  razorpayPaymentId: { type: String }
}, { timestamps: true });

PaymentSchema.index({ customerId: 1, createdAt: -1 });

export const PaymentData = mongoose.models.Payment || mongoose.model('Payment', PaymentSchema);
